#!/bin/bash

root=
chown -R root:wheel $root/Library/PreferenceBundles/DaemanPrefs.bundle
chown -R root:wheel $root/Library/PreferenceLoader/Preferences/DaemanPrefs.plist

chown root:wheel $root/Library/LaunchDaemons/chaoge.daeman.plist

if [[ -f $root/Library/LaunchDaemons/chaoge.daeman.plist ]]; then
    launchctl unload $root/Library/LaunchDaemons/chaoge.daeman.plist
fi
launchctl load $root/Library/LaunchDaemons/chaoge.daeman.plist



